exclude: |
  (?x)^(
    README.md
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: pretty-format-json
        args: ["--indent", "2", "--autofix", "--no-sort-keys"]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-metaschema
        files: ^schemas/.*\.json$
      - id: check-jsonschema
        files: ^tests/e2e/data-applications/.*\.yml$
        args: ["--schemafile", "schemas/app.schema.json"]
      - id: check-jsonschema
        files: ^tests/e2e/databricks-cluster-policies/.*\.yml$
        args: ["--schemafile", "schemas/clusterPolicy.schema.json"]
  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform fmt
        description: runs terraform fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-go
        args: ["-c", "./.terraform-docs.yml", "./"]
