name: Terraform Import Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      config:
        required: true
        type: string
        description: "Specifies the configuration folder for the deployment."
      terraform_version:
        required: true
        type: string
        description: "Specifies the terraform version."
      node_version:
        required: true
        type: number
        description: "Specifies the node version."
      working_directory:
        required: true
        type: string
        description: "Specifies the working directory."
      import_target:
        required: true
        type: string
        description: "Specifies the terraform resource address (e.g., azurerm_resource_group.my_rg)."
      resource_id:
        required: true
        type: string
        description: "Specifies the resource id to import (e.g., /subscriptions/.../resourceGroups/myResourceGroup)."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

jobs:
  deployment:
    name: Terraform Import
    runs-on: [ubuntu-latest]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    # if: github.event_name == 'push' || github.event_name == 'release'
    concurrency:
      group: terraform-${{ inputs.config }}-${{ inputs.environment }}
      cancel-in-progress: false

    env:
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_USE_OIDC: false

    steps:
      # Setup Node
      - name: Setup Node
        id: node_setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: true

      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Terraform Override
      - name: Terraform Override
        run: |
          mv docs/terraform_overrides/terraform_override.tf infrastructure/platform/

      # Terraform Init
      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform init -backend-config=../../config/${CONFIG}/azurerm.tfbackend
        env:
          CONFIG: ${{ inputs.config }}

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ vars.SUBSCRIPTION_ID }}","tenantId":"${{ vars.TENANT_ID }}"}'

      # Terraform Import
      - name: Terraform Import
        working-directory: ${{ inputs.working_directory }}
        run: |
          terraform import -var-file="../../config/${CONFIG}/vars.tfvars" -input=false '${{ inputs.import_target }}' '${{ inputs.resource_id }}'
        env:
          CONFIG: ${{ inputs.config }}
