name: Lint and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # Setup Python 3.10
      - name: Setup Python 3.10
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Setup Terraform
      - name: Setup Terraform
        id: terraform_setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.6"
          terraform_wrapper: true

      # Checkout repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Run Linting
      - name: Run Linting
        id: linting
        run: |
          pip install -r requirements.txt -q
          git init
          git add *
          pre-commit install --install-hooks
          pre-commit run --all-files --verbose
