name: Import Azure Resource into Terraform State

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Specifies the environment of the deployment."
        required: true
        type: choice
        default: "dev"
        options:
        - "dev"
      config:
        description: "Specifies the config of the deployment."
        required: true
        type: choice
        default: "."
        options:
        - "."
      import_target:
        required: true
        type: string
        description: 'Specifies the terraform resource address (e.g., azurerm_resource_group.my_rg)'
      resource_id:
        required: true
        type: string
        description: "Specifies the resource id to import (e.g., /subscriptions/.../resourceGroups/myResourceGroup)"

jobs:
  terraform_import:
    uses: ./.github/workflows/_terraformImportTemplate.yml
    name: "Dev"
    with:
      environment: ${{ inputs.environment }}
      config: ${{ inputs.config }}
      terraform_version: "1.10.4"
      node_version: 20
      working_directory: "./tests/e2e"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "9842be63-c8c0-4647-a5d1-0c5e7f8bbb25"
      import_target: ${{ inputs.import_target }}
      resource_id: ${{ inputs.resource_id }}
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
